# Generated by Django 4.1.7 on 2023-03-11 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('apt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street_number', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True)),
                ('rating_num', models.PositiveIntegerField(default=0)),
                ('amenity', models.CharField(blank=True, default=0, max_length=255)),
                ('num_bedroom', models.PositiveIntegerField(blank=True, default=0)),
                ('num_bathroom', models.PositiveIntegerField(blank=True, default=0)),
                ('capacity', models.PositiveIntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_images', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.FloatField()),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='property.property')),
            ],
        ),
    ]
