# Generated by Django 4.1.7 on 2023-04-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_availability_price_alter_property_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_number',
            field=models.CharField(max_length=50),
        ),
    ]
